version: '3.7'

services:

  productpage:
    image: 09/productpage
    ports:
      - 9080:9080
    volumes: 
      - productPage:/app
    container_name: 09-productpage
    depends_on:
      - details
      - reviews
  details:
    image: 09/details    
    container_name: 09-details
    volumes:
      - details:/opt/microservices

  reviews:
    image: 09/reviews
    container_name: 09-reviews
    depends_on:
      - ratings

  ratings:
    image: 09/ratings
    container_name: 09-ratings
    volumes:
      - product-page:/opt/microservices

volumes:
  productPage:
  details:
  prueba:
  product-page:  